
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/RDI
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rdi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kareem_19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
