
services:
  web:
    volumes:
      - .:/RDI  # Mount the project directory for local development
    
    environment:
      DJANGO_SETTINGS_MODULE: Documents.settings.development # Explicitly set the settings module
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
